
version: '3.8'

services:
  api_gateway:
    build: ./microservices/api_gateway
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - rabbitmq
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

  classification:
    build: ./microservices/classification
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads

  routing_engine:
    build: ./microservices/routing_engine
    ports:
      - "8002:8002"
    env_file: .env
    depends_on:
      - db
      - rabbitmq

  content_analysis:
    build: ./microservices/content_analysis
    ports:
      - "8003:8003"
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./uploads:/app/uploads

  workflow_integration:
    build: ./microservices/workflow_integration
    ports:
      - "8004:8004"
    env_file: .env
    depends_on:
      - db
      - rabbitmq

  web_scraper:
    build: ./microservices/web_scraper
    ports:
      - "8005:8005"
    env_file: .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: document_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage:/data

volumes:
  pgdata:
  storage:
